// Package models holds the standard model definitions for every provider.
// Names are provider-prefixed because model names collide across providers
// (e.g. Gemma, GPT-OSS, DeepSeek).
package models

import "github.com/tab58/tenzing-agent-harness/pkg/common"

type Model = common.Model

// Standard returns every compiled-in standard model definition across all
// providers. Convenience catalog only — any common.Model implementation
// works with the protocol clients.
func Standard() []common.ModelDefinition {
	return []common.ModelDefinition{
		Anthropic_ClaudeFable5.(common.ModelDefinition),
		Anthropic_ClaudeOpus5.(common.ModelDefinition),
		Anthropic_ClaudeSonnet5.(common.ModelDefinition),
		Anthropic_ClaudeHaiku4_5.(common.ModelDefinition),
		Anthropic_ClaudeOpus4_8.(common.ModelDefinition),
		Anthropic_ClaudeOpus4_7.(common.ModelDefinition),
		Anthropic_ClaudeOpus4_6.(common.ModelDefinition),
		Anthropic_ClaudeSonnet4_6.(common.ModelDefinition),
		Anthropic_ClaudeSonnet4_5.(common.ModelDefinition),
		Anthropic_ClaudeOpus4_5.(common.ModelDefinition),
		Cerebras_GPTOSS_120B.(common.ModelDefinition),
		Lightning_Nemotron3Ultra.(common.ModelDefinition),
		Lightning_Nemotron3NanoOmni_30B.(common.ModelDefinition),
		Lightning_DeepSeekV4Pro.(common.ModelDefinition),
		Lightning_Gemma4_31B.(common.ModelDefinition),
		Lightning_GPTOSS_20B.(common.ModelDefinition),
		Lightning_GPTOSS_120B.(common.ModelDefinition),
		Ollama_DeepSeekV4Flash_Cloud.(common.ModelDefinition),
		Ollama_DeepSeekV4Pro_Cloud.(common.ModelDefinition),
		Ollama_Gemma4_E2B.(common.ModelDefinition),
		Ollama_Gemma4_E4B.(common.ModelDefinition),
		Ollama_Gemma4_12B.(common.ModelDefinition),
		Ollama_Gemma4_26B.(common.ModelDefinition),
		Ollama_Gemma4_31B.(common.ModelDefinition),
		Ollama_Gemma4_Cloud.(common.ModelDefinition),
		Ollama_GLM5_1_Cloud.(common.ModelDefinition),
		Ollama_GLM5_2_Cloud.(common.ModelDefinition),
		Ollama_GLMOCR.(common.ModelDefinition),
		Ollama_Granite4_1_3B.(common.ModelDefinition),
		Ollama_Granite4_1_8B.(common.ModelDefinition),
		Ollama_Granite4_1_30B.(common.ModelDefinition),
		Ollama_KimiK2_6_Cloud.(common.ModelDefinition),
		Ollama_KimiK2_7Code_Cloud.(common.ModelDefinition),
		Ollama_LagunaS2_1.(common.ModelDefinition),
		Ollama_LagunaXS2_1.(common.ModelDefinition),
		Ollama_LFM2_24B.(common.ModelDefinition),
		Ollama_MinimaxM2_5_Cloud.(common.ModelDefinition),
		Ollama_MinimaxM2_7_Cloud.(common.ModelDefinition),
		Ollama_MinimaxM3_Cloud.(common.ModelDefinition),
		Ollama_Nemotron3Super_120B.(common.ModelDefinition),
		Ollama_Nemotron3Super_Cloud.(common.ModelDefinition),
		Ollama_Nemotron3_33B.(common.ModelDefinition),
		Ollama_Ornith_9B.(common.ModelDefinition),
		Ollama_Ornith_35B.(common.ModelDefinition),
		Ollama_Qwen3_5_0_8B.(common.ModelDefinition),
		Ollama_Qwen3_5_2B.(common.ModelDefinition),
		Ollama_Qwen3_5_4B.(common.ModelDefinition),
		Ollama_Qwen3_5_9B.(common.ModelDefinition),
		Ollama_Qwen3_5_27B.(common.ModelDefinition),
		Ollama_Qwen3_5_35B.(common.ModelDefinition),
		Ollama_Qwen3_5_122B.(common.ModelDefinition),
		Ollama_Qwen3_5_Cloud.(common.ModelDefinition),
		Ollama_Qwen3_6_27B.(common.ModelDefinition),
		Ollama_Qwen3_6_35B.(common.ModelDefinition),
		OpenAI_GPT5_6Sol.(common.ModelDefinition),
		OpenAI_GPT5_6Terra.(common.ModelDefinition),
		OpenAI_GPT5_6Luna.(common.ModelDefinition),
		OpenAI_GPT5_5.(common.ModelDefinition),
		OpenAI_GPT5_5Pro.(common.ModelDefinition),
		OpenAI_GPT5_4.(common.ModelDefinition),
		OpenAI_GPT5_4Mini.(common.ModelDefinition),
		OpenAI_GPT5_4Nano.(common.ModelDefinition),
		OpenAI_GPT5_4Pro.(common.ModelDefinition),
		OpenAI_GPT5_3ChatLatest.(common.ModelDefinition),
		OpenAI_GPT5_3Codex.(common.ModelDefinition),
		OpenAI_GPT5_2.(common.ModelDefinition),
		OpenAI_GPT5_2ChatLatest.(common.ModelDefinition),
		OpenAI_GPT5_2Codex.(common.ModelDefinition),
		OpenAI_GPT5_2Pro.(common.ModelDefinition),
		OpenAI_GPT5_1.(common.ModelDefinition),
		OpenAI_GPT5_1ChatLatest.(common.ModelDefinition),
		OpenAI_GPT5_1Codex.(common.ModelDefinition),
		OpenAI_GPT5_1CodexMax.(common.ModelDefinition),
		OpenAI_GPT5_1CodexMini.(common.ModelDefinition),
		OpenAI_GPT5.(common.ModelDefinition),
		OpenAI_GPT5ChatLatest.(common.ModelDefinition),
		OpenAI_GPT5Codex.(common.ModelDefinition),
		OpenAI_GPT5Mini.(common.ModelDefinition),
		OpenAI_GPT5Nano.(common.ModelDefinition),
		OpenAI_GPT5Pro.(common.ModelDefinition),
		OpenAI_ChatLatest.(common.ModelDefinition),
		OpenAI_O1.(common.ModelDefinition),
		OpenAI_O1Mini.(common.ModelDefinition),
		OpenAI_O1Preview.(common.ModelDefinition),
		OpenAI_O1Pro.(common.ModelDefinition),
		OpenAI_O3.(common.ModelDefinition),
		OpenAI_O3Mini.(common.ModelDefinition),
		OpenAI_O3Pro.(common.ModelDefinition),
		OpenAI_O3DeepResearch.(common.ModelDefinition),
		OpenAI_O4Mini.(common.ModelDefinition),
		OpenAI_O4MiniDeepResearch.(common.ModelDefinition),
		OpenAI_CodexMiniLatest.(common.ModelDefinition),
		OpenAI_GPT4_1.(common.ModelDefinition),
		OpenAI_GPT4_1Mini.(common.ModelDefinition),
		OpenAI_GPT4_1Nano.(common.ModelDefinition),
		OpenAI_GPT4_5Preview.(common.ModelDefinition),
		OpenAI_GPT4o.(common.ModelDefinition),
		OpenAI_GPT4oMini.(common.ModelDefinition),
		OpenAI_GPT4oSearchPreview.(common.ModelDefinition),
		OpenAI_GPT4oMiniSearchPreview.(common.ModelDefinition),
		OpenAI_ChatGPT4oLatest.(common.ModelDefinition),
		OpenAI_GPT4Turbo.(common.ModelDefinition),
		OpenAI_GPT4TurboPreview.(common.ModelDefinition),
		OpenAI_GPT4.(common.ModelDefinition),
		OpenAI_GPT3_5Turbo.(common.ModelDefinition),
		OpenAI_GPTOSS_120B.(common.ModelDefinition),
		OpenAI_GPTOSS_20B.(common.ModelDefinition),
		OpenRouter_DeepSeekV4Flash.(common.ModelDefinition),
		OpenRouter_DeepSeekV4Pro.(common.ModelDefinition),
		OpenRouter_GLM5_2.(common.ModelDefinition),
		OpenRouter_MinimaxM3.(common.ModelDefinition),
		OpenRouter_KimiK3.(common.ModelDefinition),
		OpenRouter_KimiK2_7Code.(common.ModelDefinition),
		OpenRouter_KimiK2_6.(common.ModelDefinition),
		OpenRouter_Gemma4_31B.(common.ModelDefinition),
		OpenRouter_Gemma4_26B_A4B.(common.ModelDefinition),
		OpenRouter_Gemma4_31B_Free.(common.ModelDefinition),
		OpenRouter_Gemma4_26B_A4B_Free.(common.ModelDefinition),
		OpenRouter_Grok4_5.(common.ModelDefinition),
	}
}
